// Package orgerror ...
package orgerror

import "errors"

var (
	// ErrEmployeeNotFound ...
	ErrEmployeeNotFound = errors.New("employee not found")
	// ErrDuplicateName ...
	ErrDuplicateName = errors.New("employee with this name already exists")
	// ErrInvalidDepth ...
	ErrInvalidDepth = errors.New("invalid depth")
	// ErrInvalidIncludeEmployees ...
	ErrInvalidIncludeEmployees = errors.New("invalid include_employees")
	// ErrInvalidID ...
	ErrInvalidID = errors.New("invalid id")
	// ErrInvalidMode ...
	ErrInvalidMode = errors.New("invalid mode")
	// ErrInvalidReassignToDepartmentID ...
	ErrInvalidReassignToDepartmentID = errors.New("invalid reassign_to_department_id")
	// ErrInvalidDepartmentName ...
	ErrInvalidDepartmentName = errors.New("invalid department name")
	// ErrParentNotFound ...
	ErrParentNotFound = errors.New("parent department not found")
)
