// Package orgerror ...
package orgerror

import "errors"

var (
	// ErrEmployeeNotFound ...
	ErrEmployeeNotFound = errors.New("employee not found")
	// ErrDepartmentNotFound ...
	ErrDepartmentNotFound = errors.New("department not found")
	// ErrDuplicateName ...
	ErrDuplicateName = errors.New("department with this name already exists")
	// ErrInvalidDepth ...
	ErrInvalidDepth = errors.New("invalid depth")
	// ErrInvalidIncludeEmployees ...
	ErrInvalidIncludeEmployees = errors.New("invalid include_employees")
	// ErrInvalidID ...
	ErrInvalidID = errors.New("invalid id")
	// ErrInvalidMode ...
	ErrInvalidMode = errors.New("invalid mode")
	// ErrInvalidReassignToDepartmentID ...
	ErrInvalidReassignToDepartmentID = errors.New("invalid reassign_to_department_id")
	// ErrInvalidDepartmentName ...
	ErrInvalidDepartmentName = errors.New("invalid department name")
	// ErrParentNotFound ...
	ErrParentNotFound = errors.New("parent department not found")
	// ErrInvalidFullName ...
	ErrInvalidFullName = errors.New("invalid full_name")
	// ErrInvalidPosition ...
	ErrInvalidPosition = errors.New("invalid position")
	// ErrCyclicDependency ...
	ErrCyclicDependency = errors.New("cyclic dependency detected")
	// ErrReassignTargetInSubtree ...
	ErrReassignTargetInSubtree = errors.New("reassign_to_department_id is within the deleted subtree")
)
