// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "orgstructure/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// DepartmentRepository is an autogenerated mock type for the DepartmentRepository type
type DepartmentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, dept
func (_m *DepartmentRepository) Create(ctx context.Context, dept *model.Department) error {
	ret := _m.Called(ctx, dept)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Department) error); ok {
		r0 = rf(ctx, dept)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DepartmentRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByIDs provides a mock function with given fields: ctx, ids
func (_m *DepartmentRepository) DeleteByIDs(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, id
func (_m *DepartmentRepository) Exists(ctx context.Context, id uint) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsName provides a mock function with given fields: ctx, name, parentID, excludeID
func (_m *DepartmentRepository) ExistsName(ctx context.Context, name string, parentID *uint, excludeID *uint) (bool, error) {
	ret := _m.Called(ctx, name, parentID, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint, *uint) (bool, error)); ok {
		return rf(ctx, name, parentID, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint, *uint) bool); ok {
		r0 = rf(ctx, name, parentID, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *uint, *uint) error); ok {
		r1 = rf(ctx, name, parentID, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *DepartmentRepository) GetByID(ctx context.Context, id uint) (*model.Department, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*model.Department, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *model.Department); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChildren provides a mock function with given fields: ctx, parentID
func (_m *DepartmentRepository) GetChildren(ctx context.Context, parentID uint) ([]model.Department, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []model.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]model.Department, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []model.Department); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmployees provides a mock function with given fields: ctx, departmentID, sortBy
func (_m *DepartmentRepository) GetEmployees(ctx context.Context, departmentID uint, sortBy string) ([]model.Employee, error) {
	ret := _m.Called(ctx, departmentID, sortBy)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployees")
	}

	var r0 []model.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) ([]model.Employee, error)); ok {
		return rf(ctx, departmentID, sortBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) []model.Employee); ok {
		r0 = rf(ctx, departmentID, sortBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, departmentID, sortBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubtreeIDs provides a mock function with given fields: ctx, rootID
func (_m *DepartmentRepository) GetSubtreeIDs(ctx context.Context, rootID uint) ([]uint, error) {
	ret := _m.Called(ctx, rootID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubtreeIDs")
	}

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]uint, error)); ok {
		return rf(ctx, rootID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []uint); ok {
		r0 = rf(ctx, rootID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, rootID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoveEmployees provides a mock function with given fields: ctx, fromDepartmentIDs, toDepartmentID
func (_m *DepartmentRepository) MoveEmployees(ctx context.Context, fromDepartmentIDs []uint, toDepartmentID uint) error {
	ret := _m.Called(ctx, fromDepartmentIDs, toDepartmentID)

	if len(ret) == 0 {
		panic("no return value specified for MoveEmployees")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint, uint) error); ok {
		r0 = rf(ctx, fromDepartmentIDs, toDepartmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, dept
func (_m *DepartmentRepository) Update(ctx context.Context, dept *model.Department) error {
	ret := _m.Called(ctx, dept)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Department) error); ok {
		r0 = rf(ctx, dept)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDepartmentRepository creates a new instance of DepartmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepartmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepartmentRepository {
	mock := &DepartmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
