// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "orgstructure/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// EmployeeRepository is an autogenerated mock type for the EmployeeRepository type
type EmployeeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, emp
func (_m *EmployeeRepository) Create(ctx context.Context, emp *model.Employee) error {
	ret := _m.Called(ctx, emp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Employee) error); ok {
		r0 = rf(ctx, emp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DepartmentExists provides a mock function with given fields: ctx, departmentID
func (_m *EmployeeRepository) DepartmentExists(ctx context.Context, departmentID uint) (bool, error) {
	ret := _m.Called(ctx, departmentID)

	if len(ret) == 0 {
		panic("no return value specified for DepartmentExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return rf(ctx, departmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = rf(ctx, departmentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, departmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEmployeeRepository creates a new instance of EmployeeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmployeeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmployeeRepository {
	mock := &EmployeeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
